services:
  backend:
    build:
      context: ../
      dockerfile: AspNetCoreWithReactDiffrentHost/Backend/WeatherForecast.Api/Dockerfile
    container_name: aspnet-backend
    ports:
      - 5050:8080

  frontend:
    build:
      context: ./Frontend/weatherforecast
      dockerfile: Dockerfile
    container_name: react-frontnend
    ports:
      - 9090:8080
